// screens
export const SELECT_SCREEN = "SELECT_SCREEN";

// step counter
export const SET_PEDOMETER_AVAILABILITY = "SET_PEDOMETER_AVAILABILITY";
export const SET_STEP_COUNT = "SET_STEP_COUNT";
export const SET_STEP_TARGET = "SET_STEP_TARGET";
export const SET_CALORIE_COUNT = "SET_CALORIE_COUNT";
export const STEP_COUNTER_STARTED = "STEP_COUNTER_STARTED";
export const STEP_COUNTER_RESUMED = "STEP_COUNTER_RESUMED";
export const STEP_COUNTER_PAUSED = "STEP_COUNTER_PAUSED";
export const STEP_COUNTER_STOPPED = "STEP_COUNTER_STOPPED";

// history
export const LOAD_HISTORY = "LOAD_HISTORY";
export const LOAD_HISTORY_SUCCESS = "LOAD_HISTORY_SUCCESS";
export const LOAD_HISTORY_FAILED = "LOAD_HISTORY_FAILED";
export const DELETE_HISTORY_ITEM = "DELETE_HISTORY_ITEM";
export const DELETE_HISTORY_ITEM_SUCCESS = "DELETE_HISTORY_ITEM_SUCCESS";
export const DELETE_HISTORY_ITEM_FAILED = "DELETE_HISTORY_ITEM_FAILED";
export const INSERT_HISTORY_ITEM = "INSERT_HISTORY_ITEM";
export const INSERT_HISTORY_ITEM_SUCCESS = "INSERT_HISTORY_ITEM_SUCCESS";
export const INSERT_HISTORY_ITEM_FAILED = "INSERT_HISTORY_ITEM_FAILED";

// profile
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";
